config_name: test_prompter_judge

random_seed: 20210930

load_model_path: ""

optimizer:
  type: adam
  lr: 0.00001
  cls_lr: 0.00005
  momentum: 0.9
  beta: 0.999
  weight_decay: 0


model:
  model_type: ErrPromptJudger
  pretrained_model_name: bert-base-chinese
  only_ids: False

dataset:

  train:
    type: ErrJudgePromptDataset
    text_path: ./resources/merged/clean_extend_training_input_shuf_v1.txt   #TrainingInputAll  extend_training_input_shuf clean_extend_training_input_shuf_v1
    label_path: ./resources/merged/clean_extend_training_truth_shuf_v1.txt   #TrainingTruthAll   extend_training_truth_shuf clean_extend_training_truth_shuf_v1
    error_correct: False
  test:
    type: ErrJudgePromptDataset
    text_path: ./resources/merged/TestInput.txt
    label_path: ./resources/merged/TestTruth.txt
    error_correct: False



loader:
  train:
    batch_size: 64
    shuffle: True
    call_func: sighan_error_judge_prompt
    num_workers: 4
  test:
    batch_size: 96
    shuffle: False
    call_func: sighan_error_judge_prompt
    num_workers: 4

train_paras:
  epochs: 10
  print_freq: 100
  loss: ce
  cuda_id: 1,2,3
  save_strategy: best
  save_dir: ./saved/sighan_error_judge_prompt/
  max_model_num: 3
  gamma: 0.9
  use_swa: False
  token_loss: False






