config_name: test_error_judge

random_seed: 20211205 #20210930

load_model_path: ""

optimizer:
  type: adamW
  lr: 0.00005
  cls_lr: 0.00005
  momentum: 0.9
  beta: 0.999
  weight_decay: 0


model:
  model_type: ErrPinyinCorrector
  pretrained_model_name: "bert-base-chinese"  #bert-base-chinese #clue/albert_chinese_small  clue/roberta_chinese_base
  only_ids: False
  pinyin: True
  position: True
  decoder_pinyin_ids: False
  encoder_pinyin_ids: False
  decode_on_pinyin: True

dataset:
  train:
    type: SigDataset
    text_path: ./resources/merged/clean_extend_training_input_shuf_v1.txt #./resources/merged/clean_extend_training_input_shuf_v1.txt   #TrainingInputAll  extend_training_input_shuf clean_extend_training_input_shuf_v1.txt
    label_path: ./resources/merged/clean_extend_training_truth_shuf_v1.txt #./resources/merged/clean_extend_training_truth_shuf_v1.txt   #TrainingTruthAll   extend_training_truth_shuf clean_extend_training_truth_shuf_v1.txt
  test:
    type: SigDataset
    text_path: ./resources/sighan15/TestInput.txt
    label_path: ./resources/sighan15/TestTruth.txt


loader:
  train:
    batch_size: 16
    shuffle: True
    call_func: sighan_error_detec_csc_mask_errors_random
    num_workers: 0
  test:
    batch_size: 16
    shuffle: False
    call_func: sighan_error_detec_csc
    num_workers: 0

train_paras:
  epochs: 10
  print_freq: 500
  loss: ce
  cuda_id: 3
  save_strategy: best
  save_dir: ./saved/bert-base-mask-error-pinyin/
  max_model_num: 2
  gamma: 0.9
  use_swa: True
  ContrastiveCrossEntropyLoss: False
  contastive_num: 4






